name: Link Checker for Sphinx Documentation
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          echo "Dependencies installed."

      - name: Run Sphinx linkcheck
        run: |
          cd docs
          sphinx-build -b linkcheck source _build/linkcheck

          # Check if the output file exists and extract link issues
          if [ -f _build/linkcheck/output.txt ]; then
            grep "broken" _build/linkcheck/output.txt > broken_links.txt || true
            grep "Not Found for url" _build/linkcheck/output.txt > not_found_links.txt || true
          else
            echo "Error: Linkcheck output file not found."
            exit 1
          fi

          # Display broken links if any
          if [ -s broken_links.txt ]; then
            echo "============"
            echo "Broken links"
            echo "============"
            cat broken_links.txt
          fi

          # Display not-found links if any
          if [ -s not_found_links.txt ]; then
            echo "==============="
            echo "Not Found Links"
            echo "==============="
            cat not_found_links.txt
          fi

          # Set exit code based on presence of broken/not-found links
          if [ -s broken_links.txt ] || [ -s not_found_links.txt ]; then
            echo "Broken links found."
            exit 1
          else
            echo "No broken links found."
          fi
