name: Link Checker for Sphinx Documentation
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          echo "Dependencies installed."

      - name: Run Sphinx linkcheck
        run: |
          cd docs
          sphinx-build -b linkcheck source _build/linkcheck > /dev/null 2>&1 || true  # Suppress full output

          grep "broken" _build/linkcheck/output.txt > broken_links.txt                # Extract broken links
          grep "Not Found for url" _build/linkcheck/output.txt > not_found_links.txt  # Extract not found links

          # -s flag checks if the file is not empty.
          if [ -s broken_links.txt ]; then
            echo "============"
            echo "Broken Links"
            echo "============"
            cat broken_links.txt
          fi

          if [ -s not_found_links.txt ]; then
            echo "==============="
            echo "Not Found Links"
            echo "==============="
            cat not_found_links.txt
          fi

          # Exit with error if any broken or not found links exist
          if [ -s broken_links.txt ] || [ -s not_found_links.txt ]; then
            echo "Broken links found."
            exit 1

          else
            echo "No broken links found."
          fi
